from pathlib import Path
from .config import Config


class SemiSupervisedConfig(Config):

    EXCLUDE_MABE22 = False

    USE_AUTOENCODER = True
    AUTOENCODER_LATENT_DIM = 128
    AUTOENCODER_HIDDEN_CHANNELS = [256, 256, 256, 256]
    AUTOENCODER_SEQ_LEN = 90
    AUTOENCODER_BATCH_SIZE = 64
    AUTOENCODER_EPOCHS = 50
    AUTOENCODER_LR = 0.001
    AUTOENCODER_BETA = 0.5
    AUTOENCODER_PATIENCE = 10

    USE_PSEUDO_LABELING = True
    PSEUDO_LABEL_CONFIDENCE = 0.85
    PSEUDO_LABEL_ITERATIONS = 3
    PSEUDO_LABEL_MIN_THRESHOLD = 0.7
    PSEUDO_LABEL_MAX_THRESHOLD = 0.95


class AutoencoderOnlyConfig(Config):

    EXCLUDE_MABE22 = False

    USE_AUTOENCODER = True
    AUTOENCODER_LATENT_DIM = 128
    AUTOENCODER_HIDDEN_CHANNELS = [256, 256, 256, 256]
    AUTOENCODER_SEQ_LEN = 90
    AUTOENCODER_BATCH_SIZE = 64
    AUTOENCODER_EPOCHS = 50
    AUTOENCODER_LR = 0.001
    AUTOENCODER_BETA = 0.5
    AUTOENCODER_PATIENCE = 10

    USE_PSEUDO_LABELING = False


class PseudoLabelingOnlyConfig(Config):

    EXCLUDE_MABE22 = False

    USE_AUTOENCODER = False

    USE_PSEUDO_LABELING = True
    PSEUDO_LABEL_CONFIDENCE = 0.85
    PSEUDO_LABEL_ITERATIONS = 3
    PSEUDO_LABEL_MIN_THRESHOLD = 0.7
    PSEUDO_LABEL_MAX_THRESHOLD = 0.95
